#!/usr/bin/env bash
# Shared commit-message validator. Reads a message on stdin and enforces the
# repository's commit rules. Sourced by both the local git commit-msg hook and
# the editor pre-commit guard so the two layers can never drift.
#
# Hard failures (exit 1): non-Conventional-Commit header, trailing period on the
# subject, or an attribution trailer. Warnings (exit 0): subject over 50 chars,
# or a scope outside the known set.
set -euo pipefail

readonly TYPES='feat|fix|docs|style|refactor|perf|test|build|ci|chore'
readonly KNOWN_SCOPES=" domain db auth floorplan crypto i18n notify jobs ui config observability web worker app frontend server ci dev deps release "

msg="$(cat)"
first_line="${msg%%$'\n'*}"

fail() {
    printf 'commit rejected: %s\n' "$1" >&2
    exit 1
}

warn() {
    printf 'commit warning: %s\n' "$1" >&2
}

# Attribution scan over the whole message (case-insensitive). High-signal
# patterns only, so legitimate words such as "email"/"available" never trip it.
lower="$(printf '%s' "$msg" | tr '[:upper:]' '[:lower:]')"
# Strip the repo's own tool filenames (.claude/, CLAUDE.md) so referencing them
# in a message is not mistaken for an assistant mention.
scan="${lower//claude.md/}"
scan="${scan//.claude/}"
for pat in 'claude' 'anthropic' 'co-authored-by:' 'generated with' 'generated by'; do
    case "$scan" in
        *"$pat"*) fail "attribution detected (\"$pat\"); commits are authored by the human only" ;;
    esac
done
case "$msg" in
    *🤖*) fail "attribution emoji detected; commits are authored by the human only" ;;
esac

# Merge/revert/fixup summaries are exempt from the Conventional-Commit shape.
case "$first_line" in
    'Merge '* | 'Revert '* | 'fixup! '* | 'squash! '*) exit 0 ;;
esac

if [[ ! "$first_line" =~ ^($TYPES)(\([a-z0-9._-]+\))?(!)?:\ .+ ]]; then
    fail "header must be Conventional Commits — type(scope): subject
  allowed types: $TYPES
  e.g. feat(db): add booking index
  got: $first_line"
fi

[[ "$first_line" =~ \.$ ]] && fail "subject must not end with a period
  got: $first_line"

if (( ${#first_line} > 50 )); then
    warn "subject is ${#first_line} chars (target ≤50): $first_line"
fi

if [[ "$first_line" =~ ^[a-z]+\(([a-z0-9._-]+)\) ]]; then
    scope="${BASH_REMATCH[1]}"
    case "$KNOWN_SCOPES" in
        *" $scope "*) ;;
        *) warn "scope \"$scope\" is not a known crate/app or cross-cutting scope" ;;
    esac
else
    warn "no scope given; prefer type(scope): — scope is a crate or app"
fi

exit 0
