//! shadcn Base UI components. Each module is transcribed 1:1 from the archived
//! Base UI source in `crates/ui/reference/shadcn/ui`. Children are declared here;
//! the crate root (`lib.rs`) re-exports their public items flat (`ui::Button`, …).
//! Grows wave by wave.

pub mod accordion;
pub mod alert;
pub mod aspect_ratio;
pub mod avatar;
pub mod badge;
pub mod breadcrumb;
pub mod button;
pub mod button_group;
pub mod calendar;
pub mod card;
pub mod checkbox;
pub mod collapsible;
pub mod combobox;
pub mod command;
pub mod context_menu;
pub mod date_picker;
pub mod dialog;
pub mod direction;
pub mod drawer;
pub mod dropdown_menu;
pub mod empty;
pub mod field;
pub mod hover_card;
pub mod input;
pub mod input_group;
pub mod input_otp;
pub mod item;
pub mod kbd;
pub mod label;
pub mod menubar;
pub mod native_select;
pub mod navigation_menu;
pub mod pagination;
pub mod popover;
pub mod progress;
pub mod radio_group;
pub mod resizable;
pub mod select;
pub mod separator;
pub mod sheet;
pub mod skeleton;
pub mod slider;
pub mod sonner;
pub mod spinner;
pub mod switch;
pub mod table;
pub mod tabs;
pub mod textarea;
pub mod toggle;
pub mod toggle_group;
pub mod tooltip;
